In [3]:
import pandas as pd
from usagrid import s3


#Generation
df = s3.read_pyarrow_from_s3(bucket_name="usagrid",key="silver/PJM/PJM_generation.arrow").to_pandas()

In [4]:
df

,datetime_beginning_ept,fuel_type,mw,fuel_percentage_of_total,is_renewable
datetime_beginning_utc,,,,,
2018-01-01 05:00:00,2018-01-01 00:00:00,Wind,3906.0,0.030,True
2018-01-01 05:00:00,2018-01-01 00:00:00,Coal,48546.0,0.420,False
2018-01-01 05:00:00,2018-01-01 00:00:00,Gas,23379.0,0.200,False
2018-01-01 05:00:00,2018-01-01 00:00:00,Hydro,695.0,0.010,True
2018-01-01 05:00:00,2018-01-01 00:00:00,Multiple Fuels,5.0,0.000,False
...,...,...,...,...,...
2024-06-19 21:00:00,2024-06-19 17:00:00,Oil,2036.0,0.010,False
2024-06-19 21:00:00,2024-06-19 17:00:00,Other Renewables,626.0,0.000,True
2024-06-19 21:00:00,2024-06-19 17:00:00,Solar,5720.0,0.039,True
2024-06-19 21:00:00,2024-06-19 17:00:00,Storage,15.0,0.000,False
2024-06-19 21:00:00,2024-06-19 17:00:00,Wind,1057.0,0.010,True